SELECT    SUM((A+B)/C-S) ,
          COUNT(DOCTYPE.SEQID) SIDDD,
          SUM(DOCTYPE.DOCTYPEID+DOC.ATTACHEDTOOBJECTID) AS TYPEID,
          DOC.ATTACHEDTOOBJECTID AS PROJECTID ,
          DOCTYPE.DOCTYPENAME AS TYPENAME,
          DOC.FILENAME,
          DOC.RECORDTIME,
          DOC.RECORDMEN,
          DOC.DOCID,
          (SELECT MAX(ASD) FROM TABLE_GG WHERE A=DOC.DOCID) CDDDDDDD
  FROM  TABLE_ABCS,
  ( SELECT CHILDDOC.DOCTYPEID,PARENTDOC.DOCTYPENAME,SEQID,CHILDDOC.DOCTYPENAME DOCTYPENM,PARENTDOC.SEQID SEQ
    FROM
      (SELECT DOCTYPEID,DOCTYPENAME,SEQID FROM PM_T_DOCUMENTTYPE WHERE PROJECTTYPEID=1 AND SEQID IS NOT NULL ) PARENTDOC,
      (SELECT DOCTYPEID,DOCTYPENAME,PARENTDOCTYPE FROM PM_T_DOCUMENTTYPE WHERE PROJECTTYPEID=1 AND SEQID IS  NULL ) CHILDDOC
   WHERE CHILDDOC.PARENTDOCTYPE=PARENTDOC.DOCTYPEID ) DOCTYPE
  LEFT JOIN
  (SELECT DOCID_DD  DOCID,DOCTYPEID,FILENAME,ATTACHEDTOOBJECTID,RECORDTIME ,RECORDMEN FROM (SELECT DOCID_DD,DOCTYPEID,FILENAME,ATTACHEDTOOBJECTID,RECORDTIME ,RECORDMEN FROM PM_T_DOCUMENTS) DOCC ) DOC
  ON DOC.DOCTYPEID=DOCTYPE.DOCTYPEID ORDER BY SEQID DESC,DOC.DOCTYPEID
