
/*SELECT A,B,C.C,B.D,E,CC1 FROM TAB_A,TAB_B  B,(SELECT CC1,C,CC3 FROM ( SELECT CC1,CC2 C,CC3 FROM TAB_C C,TAB_D D) TAB_CC) C*/
/**/
SELECT (SELECT SUM(PP.P_A+PP.P_C) FROM (SELECT P_A,P_B,P_C FROM P_TABLE) PP) CUT_A, PRE_A+RPE_B+SUM(PRE_D+PRE_C) SUM_A, PRE_A+RPE_B+PRE_C A_EXP , TT2.A, TT1.B, C, TT2.D , SUB2_D , SUB2_B, F, H, SUB3_C, H3, MAX(H) MX_H FROM TAB_ABCD TT1,TAB_AB TT2,
    (SELECT SUB_D,SUB_B,SUB_C,F FROM TAB_FF) SUB,
    (SELECT SUB2_D,SUB3_C,H ,SUB3_D,SUB3_C,H3 FROM (SELECT SUB2_D,SUB2_B,SUB2_C,H FROM TAB_FFSUB2) SUB2_S ,
    (SELECT SUB3_D,SUB3_B,SUB3_C,H3 FROM TAB_FFSUB3) SUB3_S) SUB2


/*
SELECT SUM((A + B) / C - S), COUNT(DOCTYPE.SEQID) SIDDD, SUM(DOCTYPE.DOCTYPEID + DOC.ATTACHEDTOOBJECTID) AS TYPEID, DOC.ATTACHEDTOOBJECTID AS PROJECTID, DOCTYPE.DOCTYPENAME AS TYPENAME, DOC.FILENAME, DOC.RECORDTIME, DOC.RECORDMEN, DOC.DOCID, (
		SELECT ASD
		FROM TABLE_GG
		WHERE A = DOC.DOCID
		) CDDDDDDD
FROM (
	SELECT DOCTYPEID, DOCTYPENAME, SEQID, DOCTYPENAME DOCTYPENM, SEQID SEQ
	FROM  PM_T_DOCUMENTS002)DOCTYPE

LEFT JOIN (
	SELECT DOCID, DOCTYPEID, FILENAME, ATTACHEDTOOBJECTID, RECORDTIME, RECORDMEN
	FROM PM_T_DOCUMENTS003
	WHERE DOCTYPE = 3
		AND ATTACHEDTOOBJECTID = $C (NAME = ATTOBJID)
	) DOC ON DOC.DOCTYPEID = DOCTYPE.DOCTYPEID
ORDER BY SEQID DESC, DOC.DOCTYPEID;
*/